name: Cosign Image on Push

on:
  push:
    branches:
      - main

jobs:
  sign-and-verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install cosign
      uses: sigstore/cosign-installer@main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: softveda/learn-sigstore_ch2:latest

    - name: Build and Sign the Image
      run: |
        docker build -t learn-sigstore_ch2:latest .
        cosign sign --key cosign.key learn-sigstore_ch2:latest
        docker push learn-sigstore_ch2:latest

    - name: Verify Image Signature
      run: cosign verify --key cosign.pub learn-sigstore_ch2:latest