name: Cosign Image on Push

on:
  push:
    branches:
      - main

jobs:
  sign-and-verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.5.0
    
    - name: Check cosign install!
      run: cosign version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: softveda/learn-sigstore_ch2:latest

    - name: Build and Sign the Image
      run: |
        cosign sign -y env://COSIGN_PVT_KEY softveda/learn-sigstore_ch2:latest
      env:
        COSIGN_PVT_KEY: ${{ secrets.COSIGN_PVT_KEY }}

    - name: Verify Image Signature
      run: cosign verify --key env://COSIGN_PUB_KEY softveda/learn-sigstore_ch2:latest
      env:
        COSIGN_PUB_KEY: ${{ secrets.COSIGN_PUB_KEY }}